id: P001666
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 2021-12-17 10:13:26.234067
source_metadata:
  id: bdr:W21846
  title: ཞང་ཞུང་སྲིད་པའི་གྲེ་འགྱུར།
  author: ''
  volumes:
    155bc8eb3a0e4eecbdf7acc2e6683ba2:
      image_group_id: I1KG16014
      title: ''
      volume_number: 1
      total_pages: 512
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
