id: I0B27F0E3
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T17:30:33+00:00'
last_modified: '2022-06-07T13:57:19.406072+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W21846
  title: ཞང་ཞུང་སྲིད་པའི་གྲེ་འགྱུར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    EE82:
      image_group_id: I1KG16014
      title: ''
      total_pages: 512
      order: 1
      base_file: EE82.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
